# Generated by Django 4.2.4 on 2023-09-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='локація')),
                ('slug', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'локація',
                'verbose_name_plural': 'локації',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='назва пошуку')),
                ('slug', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'пошук',
                'verbose_name_plural': 'назва пошуку',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='посилання')),
                ('title', models.CharField(max_length=100, verbose_name='назва вакансії')),
                ('company', models.CharField(max_length=50, verbose_name='компанія')),
                ('description', models.TextField(verbose_name='опис')),
                ('salary', models.CharField(max_length=50, verbose_name='оплата')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.location')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.search')),
            ],
            options={
                'verbose_name': 'назва вакансії',
                'verbose_name_plural': 'назва вакансії',
            },
        ),
    ]
