# Generated by Django 4.2.4 on 2023-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_vacancy_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'пошук', 'verbose_name_plural': 'пошук'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'назва вакансії', 'verbose_name_plural': 'вакансії'},
        ),
    ]
