# Generated by Django 4.2.4 on 2023-09-11 22:06

from django.db import migrations, models
import django.db.models.deletion
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_errors_alter_search_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errors',
            options={'verbose_name': 'Помилка', 'verbose_name_plural': 'Помилки'},
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default=scraping.models.default_urls)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.location')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.search')),
            ],
            options={
                'unique_together': {('location', 'search')},
            },
        ),
    ]
